name: Reddit RSS Tracker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '14,27,43,56 * * * *'

jobs:
  track-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS tracker
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python reddit_rss_tracker.py

      - name: Display debug log
        run: cat debug.log
        if: always()

      - name: Upload debug log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-log
          path: debug.log

      - name: Upload comparison result
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: comparison-result
          path: comparison_result.json

      - name: Commit and push if there are changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add reddit_posts.db
          git commit -m "Update RSS feed data" || echo "No changes to commit"
          git push
